"""Weeks 1-4 Python Fundamentals quizzes (15 easy MCQs each), written from the
Session 01-04 slide decks. Each question: (text, correct, [3 wrong], explanation).
The correct answer is listed first here and shuffled deterministically on seed."""

PYTHON_FUNDAMENTALS_QUIZZES = [
    {
        'week': 1,
        'title': 'Week 1 Quiz — Python Basics',
        'description': 'Variables, data types, lists, dictionaries and f-strings.',
        'questions': [
            ('What does type(9.99) return in Python?', "<class 'float'>",
             ["<class 'int'>", "<class 'str'>", "<class 'bool'>"],
             '9.99 has a decimal point, so it is a float.'),
            ('Which is the best variable name for the total sales of one day?', 'daily_sales',
             ['x', 'Daily Sales', '1sales'],
             'Use lowercase, underscores and a descriptive name. Names cannot contain spaces or start with a number.'),
            ('What does print("5" + "5") show?', '55',
             ['10', '5', 'An error'],
             'Both values are strings, so + joins them together instead of adding.'),
            ('Which data type holds only True or False?', 'bool',
             ['int', 'str', 'float'],
             'bool (boolean) has exactly two values: True and False.'),
            ('menu = ["Big Mac", "McFlurry", "Fries"]. What does menu[0] give?', '"Big Mac"',
             ['"McFlurry"', '"Fries"', 'An error'],
             'List positions start at 0, so index 0 is the first item.'),
            ('Which index gets the LAST item of a list?', '-1',
             ['0', '1', 'last'],
             'A negative index counts from the end, so -1 is the last item.'),
            ('Which method adds a new item to the end of a list?', 'append()',
             ['remove()', 'sorted()', 'len()'],
             'menu.append("Apple Pie") adds the item to the end of the list.'),
            ('How do you create a dictionary?', 'Curly braces with key: value pairs',
             ['Square brackets with items', 'Round brackets with items', 'Quotes around a sentence'],
             'A dictionary looks like {"name": "Big Mac", "price": 5.99}.'),
            ('burger = {"name": "Big Mac", "price": 5.99}. How do you get the price?', 'burger["price"]',
             ['burger[1]', 'burger.price', 'price(burger)'],
             'Dictionary values are looked up by their key name.'),
            ('Which is the safe way to read a dictionary key that might be missing?', '.get()',
             ['.remove()', '.append()', '.sorted()'],
             'burger.get("size", "unknown") returns "unknown" instead of crashing when the key is missing.'),
            ('What does f"{sales:.2f}" do?', 'Shows sales with 2 decimal places',
             ['Rounds sales to a whole number', 'Multiplies sales by 2', 'Turns sales into text only'],
             '.2f means a float with 2 digits after the decimal point.'),
            ('What is the difference between = and == ?', '= assigns a value, == compares two values',
             ['= compares, == assigns', 'They mean the same thing', '= is for text, == is for numbers'],
             'x = 5 stores 5 in x. x == 5 asks whether x equals 5 (True or False).'),
            ('Why does print("Price: " + 9.99) give an error?', 'You cannot join text and a number with +',
             ['9.99 is not a valid number', 'print cannot show decimals', 'Text needs single quotes'],
             'Mixing str and float causes a TypeError. Use an f-string instead: f"Price: {9.99}".'),
            ('What does len(["a", "b", "c"]) return?', '3',
             ['2', '4', '"abc"'],
             'len() counts how many items are in the list.'),
            ('Why is Python so popular for data science?', 'It is easy to read and has many free libraries',
             ['It is the fastest language ever made', 'It can only be used for data', 'It needs no computer to run'],
             'Readable code plus libraries like pandas, numpy and scikit-learn make it the top choice.'),
        ],
    },
    {
        'week': 2,
        'title': 'Week 2 Quiz — Control Flow',
        'description': 'if / elif / else decisions, for loops and while loops.',
        'questions': [
            ('What does control flow let your code do?', 'Make decisions and repeat actions',
             ['Run faster', 'Change the file name', 'Draw pictures'],
             'if/else make decisions and loops repeat actions automatically.'),
            ('Which keyword checks an extra condition after an if?', 'elif',
             ['else if', 'elseif', 'then'],
             'Python uses elif (short for else if).'),
            ('temperature = 28. The code is: if temperature > 30 -> "Heatwave", elif temperature > 22 -> "Warm", else -> "Cold". What prints?', 'Warm',
             ['Heatwave', 'Cold', 'Nothing'],
             '28 is not above 30, but it is above 22, so the elif branch runs.'),
            ('sales = 850. Grades: >= 2000 Excellent, >= 1400 Good, >= 1000 Average, otherwise Below target. What is the grade?', 'Below target',
             ['Average', 'Good', 'Excellent'],
             '850 is lower than 1000, so none of the if/elif conditions match and else runs.'),
            ('is_weekend = True and is_raining = False. What is (is_weekend and not is_raining)?', 'True',
             ['False', 'None', 'An error'],
             'not False is True, and True and True is True.'),
            ('Which loop is best for doing something for EVERY item in a list?', 'for loop',
             ['while loop', 'if statement', 'print statement'],
             'A for loop visits each item in a collection one by one.'),
            ('What numbers does range(5) produce?', '0, 1, 2, 3, 4',
             ['1, 2, 3, 4, 5', '0, 1, 2, 3, 4, 5', '5'],
             'range(5) starts at 0 and stops before 5.'),
            ('What does this code print? for i in range(3): print(i + 1)', '1 2 3 (each on its own line)',
             ['0 1 2', '1 2 3 4', '3'],
             'i is 0, 1, 2, so i + 1 prints 1, 2, 3.'),
            ('What does total += price do?', 'Adds price to total',
             ['Replaces total with price', 'Subtracts price from total', 'Compares total and price'],
             'total += price is the same as total = total + price.'),
            ('What does enumerate() give you when looping?', 'The index number and the item',
             ['Only the item', 'Only the total count', 'A sorted list'],
             'for i, item in enumerate(menu) gives both the position and the value.'),
            ('A while loop keeps running as long as...', 'its condition is True',
             ['it runs 10 times', 'the list is empty', 'the program is closed'],
             'while checks the condition each time and stops when it becomes False.'),
            ('stock = 3. while stock > 0: stock -= 1. How many times does the loop run?', '3 times',
             ['2 times', '4 times', 'Forever'],
             'stock goes 3 to 2 to 1 to 0, so the loop body runs 3 times.'),
            ('What does break do inside a loop?', 'Exits the loop immediately',
             ['Skips to the next item', 'Restarts the program', 'Deletes the loop'],
             'break stops the loop right away, even if the condition is still True.'),
            ('What is an infinite loop?', 'A loop whose condition never becomes False',
             ['A loop that runs exactly once', 'A loop with no code inside', 'A loop that uses range()'],
             'It freezes your program, so always make sure the loop can end or include a break.'),
            ('What does [p * 0.9 for p in prices] create?', 'A new list with every price at 90% (10% off)',
             ['A single number', 'A dictionary of prices', 'An error'],
             'A list comprehension is a compact loop that builds a new list.'),
        ],
    },
    {
        'week': 3,
        'title': 'Week 3 Quiz — Data Structures & Functions',
        'description': 'Lists, tuples, dictionaries, functions and modules.',
        'questions': [
            ('What is the main difference between a list and a tuple?', 'A tuple cannot be changed after it is created',
             ['A tuple can only hold numbers', 'A list is always faster', 'A tuple has no order'],
             'Tuples are immutable (locked). Lists can be changed.'),
            ('Which brackets create a tuple?', 'Round brackets ( )',
             ['Square brackets [ ]', 'Curly braces { }', 'Angle brackets < >'],
             'coords = (51.5, -0.12) is a tuple.'),
            ('coords = (1, 2, 3). What happens when you run coords[0] = 99?', 'TypeError — tuples cannot be changed',
             ['coords becomes (99, 2, 3)', 'coords becomes empty', 'Nothing happens'],
             'Tuples are immutable, so item assignment is not allowed.'),
            ('Which one is a tuple with ONE element?', '(42,)',
             ['(42)', '[42]', '{42}'],
             'The comma makes it a tuple. (42) is just the number 42 in brackets.'),
            ('lat, lon = (51.5, -0.12). What is this called?', 'Unpacking',
             ['Slicing', 'Looping', 'Importing'],
             'Unpacking assigns each element of a tuple to its own variable.'),
            ('menu = ["Big Mac", "McFlurry", "Fries", "Coke"]. What is menu[1:]?', '["McFlurry", "Fries", "Coke"]',
             ['["Big Mac"]', '["Big Mac", "McFlurry"]', '["Fries", "Coke"]'],
             'A slice from index 1 with no end goes to the end of the list.'),
            ('What does menu.pop() do?', 'Removes and returns the last item',
             ['Adds an item to the front', 'Sorts the list', 'Empties the whole list'],
             'pop() takes the last item out of the list and gives it back to you.'),
            ('What must be true about dictionary keys?', 'They must be unique',
             ['They must be numbers', 'They must be sorted', 'They must be lowercase'],
             'Each key can only appear once in a dictionary.'),
            ('d = {"name": "Big Mac"}. What happens with d["calories"]?', 'KeyError — the key does not exist',
             ['It returns 0', 'It returns None', 'It adds the key'],
             'Use d.get("calories", 0) to avoid the crash.'),
            ('Which structure is best for named data like a burger\'s name, price and calories?', 'Dictionary',
             ['Tuple', 'List of numbers', 'String'],
             'Dictionaries store data by name, e.g. burger["calories"].'),
            ('Which structure is best for GPS coordinates that must never change?', 'Tuple',
             ['List', 'Dictionary', 'Boolean'],
             'Fixed data that must not change belongs in a tuple.'),
            ('Which keyword defines a function?', 'def',
             ['func', 'function', 'define'],
             'def greet(name): starts a function definition.'),
            ('What does return do in a function?', 'Sends a value back to where the function was called',
             ['Stops the whole program', 'Prints the value on screen', 'Deletes the function'],
             'return gives the result back so you can store or use it.'),
            ('In def calculate_total(price, quantity, tax=0.10), what is tax=0.10?', 'A default parameter value',
             ['A required argument', 'A list', 'A syntax error'],
             'If you do not pass tax, Python uses 0.10 automatically.'),
            ('What does import math; math.sqrt(144) return?', '12.0',
             ['144', '72.0', '1.44'],
             'math.sqrt gives the square root: 12 x 12 = 144.'),
        ],
    },
    {
        'week': 4,
        'title': 'Week 4 Quiz — NumPy & Pandas',
        'description': 'NumPy arrays, Pandas Series and DataFrames, cleaning, groupby and merge.',
        'questions': [
            ('Why is NumPy faster than a normal Python list for maths?', 'It does the maths on the whole array at once, without a Python loop',
             ['It stores only small numbers', 'It skips the calculation', 'It uses less RAM only'],
             'NumPy is vectorised: the loop runs in fast compiled code.'),
            ('a = np.array([1, 2, 3]). What is a * 2?', '[2 4 6]',
             ['[1 2 3 1 2 3]', '[1 2 3 2]', 'An error'],
             'Vectorised maths applies the operation to every element.'),
            ('What is a.shape for an array with 5 numbers in one row?', '(5,)',
             ['(1, 1)', '5', '(0, 5)'],
             'shape shows the size of each dimension. One dimension of 5 is (5,).'),
            ('For a 2D array m, what does m[0, :] give?', 'The first row',
             ['The first column', 'The last row', 'The whole array'],
             'Format is [row, column]. 0 picks row 0 and : means all columns.'),
            ('What does m.sum(axis=0) do on a 2D array?', 'Adds up each column',
             ['Adds up each row', 'Adds every number into one total', 'Sorts the array'],
             'axis=0 collapses the rows, giving one total per column.'),
            ('scores = np.array([45, 82, 67, 91]). What does scores[scores > 70] return?', '[82 91]',
             ['[45 67]', '[True True]', '[70]'],
             'A boolean mask keeps only the elements where the condition is True.'),
            ('What is a Pandas Series?', 'One column of labelled data',
             ['A whole spreadsheet', 'A type of chart', 'A Python loop'],
             'A Series is 1D data with an index. Every DataFrame column is a Series.'),
            ('What is a DataFrame best described as?', 'A table with rows and columns, like an Excel sheet',
             ['A single number', 'A picture file', 'A Python function'],
             'DataFrames hold rows and columns of data, and can be sorted, filtered and grouped.'),
            ('What does pd.read_csv("menu.csv") do?', 'Loads the CSV file into a DataFrame',
             ['Deletes the CSV file', 'Saves a new CSV file', 'Prints the file name'],
             'read_csv is the most common way to load data into Pandas.'),
            ('What does df.head() show?', 'The first 5 rows',
             ['The last 5 rows', 'The column names only', 'The total row count'],
             'head() shows the first rows so you can quickly peek at the data.'),
            ('What does df.isnull().sum() tell you?', 'How many missing values are in each column',
             ['The total of all numbers', 'How many rows there are', 'Which columns are text'],
             'isnull() marks missing values and sum() counts them per column.'),
            ('What is the difference between loc and iloc?', 'loc uses labels, iloc uses integer positions',
             ['loc is for rows, iloc is for columns', 'loc is faster, iloc is slower', 'They are exactly the same'],
             'Use loc for names/conditions and iloc for position numbers.'),
            ('What does df.dropna() do?', 'Removes rows that have missing values',
             ['Fills missing values with 0', 'Deletes the whole DataFrame', 'Renames the columns'],
             'dropna() drops rows containing NaN. Use fillna() to fill instead.'),
            ('What does df.groupby("category")["calories"].mean() calculate?', 'The average calories for each category',
             ['The total calories overall', 'The number of categories', 'The highest calorie item'],
             'groupby splits the data into groups, then mean() is applied to each group.'),
            ('What does pd.merge(orders, menu, on="item_id") do?', 'Joins the two tables using the shared item_id column',
             ['Stacks the tables on top of each other', 'Deletes the item_id column', 'Sorts both tables'],
             'merge works like a SQL JOIN: it matches rows using a common column.'),
        ],
    },
]

assert all(len(q['questions']) == 15 for q in PYTHON_FUNDAMENTALS_QUIZZES), 'each quiz needs 15 questions'
